## Maman 14 Makefile 
## By Dor Laska (305465775) & Stas Seldin (311950943)

assembler.o: main.c
	gcc hash.c consts.h utils.c init.c read_file.c firstScan.c secondScan.c output.c main.c -Wall -g -ansi -o assembler
